package main

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/fatih/color"
	"github.com/schollz/progressbar/v3"
	"github.com/spf13/cobra"

	"github.com/Siddhant-K-code/gemma-vision/internal/ollama"
)

var (
	outlineAudience string
	outlineTone     string
	outlineOut      string
)

var outlineCmd = &cobra.Command{
	Use:   "outline <image> [image...]",
	Short: "Generate a blog post outline from one or more images",
	Long: `Analyse one or more images (whiteboard photos, diagrams, slides, screenshots)
and produce a structured blog post outline using gemma4:12b vision.

The outline includes:
  • 3 title options
  • Hook / opening paragraph suggestion
  • H2 sections with key points per section
  • Suggested conclusion + CTA
  • SEO keyword suggestions

Pass multiple images to treat them as a sequence (e.g. a slide deck).`,
	Args: cobra.MinimumNArgs(1),
	RunE: runOutline,
}

func init() {
	outlineCmd.Flags().StringVar(&outlineAudience, "audience", "software engineers", "Target audience for the post")
	outlineCmd.Flags().StringVar(&outlineTone, "tone", "technical but conversational", "Writing tone")
	outlineCmd.Flags().StringVar(&outlineOut, "out", "", "Write outline to a markdown file instead of stdout")
}

func buildOutlinePrompt(audience, tone string, imageCount int) string {
	imageDesc := "this image"
	if imageCount > 1 {
		imageDesc = fmt.Sprintf("these %d images in sequence", imageCount)
	}

	return fmt.Sprintf(`You are a technical blog post strategist. Analyse %s and produce a structured blog post outline.

Target audience: %s
Tone: %s

Output the outline in this exact markdown format:

## Title Options
1. [title option 1]
2. [title option 2]
3. [title option 3]

## Hook
[1-2 sentence opening that grabs attention]

## Sections
### [Section 1 Title]
- [key point]
- [key point]
- [key point]

### [Section 2 Title]
- [key point]
- [key point]

### [Section 3 Title]
- [key point]
- [key point]

(add more sections as needed based on the content)

## Conclusion
[What the reader should take away and do next]

## CTA
[One clear call to action]

## SEO Keywords
[5-8 comma-separated keywords]

Output only the markdown outline. No preamble, no commentary.`, imageDesc, audience, tone)
}

func runOutline(cmd *cobra.Command, args []string) error {
	// Validate all args are image files
	for _, p := range args {
		if !imageExts[strings.ToLower(fmt.Sprintf("%s", getExt(p)))] {
			return fmt.Errorf("%s is not a supported image file (jpg, png, webp, gif, bmp)", p)
		}
		if _, err := os.Stat(p); err != nil {
			return err
		}
	}

	client := ollama.New(ollamaHost, ollamaModel)

	bold := color.New(color.Bold)
	cyan := color.New(color.FgCyan)
	dim := color.New(color.Faint)

	bold.Fprintf(os.Stderr, "Analysing %d image(s) with %s…\n", len(args), ollamaModel)
	dim.Fprintf(os.Stderr, "Audience: %s | Tone: %s\n\n", outlineAudience, outlineTone)

	spinner := progressbar.NewOptions(-1,
		progressbar.OptionSetDescription("  Thinking"),
		progressbar.OptionSpinnerType(14),
		progressbar.OptionSetWriter(os.Stderr),
	)
	done := make(chan struct{})
	go func() {
		for {
			select {
			case <-done:
				return
			default:
				_ = spinner.Add(1)
				time.Sleep(80 * time.Millisecond)
			}
		}
	}()

	start := time.Now()
	prompt := buildOutlinePrompt(outlineAudience, outlineTone, len(args))
	outline, err := client.Ask(prompt, args)
	close(done)
	_ = spinner.Clear()

	if err != nil {
		return fmt.Errorf("outline generation failed: %w", err)
	}
	outline = strings.TrimSpace(outline)

	elapsed := time.Since(start).Round(time.Millisecond)
	dim.Fprintf(os.Stderr, "Generated in %s\n\n", elapsed)

	if outlineOut != "" {
		header := fmt.Sprintf("<!-- Generated by gemma-vision outline | %s -->\n\n", time.Now().Format("2006-01-02"))
		if err := os.WriteFile(outlineOut, []byte(header+outline+"\n"), 0644); err != nil {
			return err
		}
		cyan.Fprintf(os.Stderr, "Outline written to %s\n", outlineOut)
	} else {
		fmt.Println(outline)
	}

	return nil
}

func getExt(path string) string {
	for i := len(path) - 1; i >= 0; i-- {
		if path[i] == '.' {
			return path[i:]
		}
	}
	return ""
}
